### ISSUE TITLE
Stroop

### ISSUE THREAD

**Issue by valerio-bozzolan** [fkropfhamer/brainjogging#2]
Hi all!

I noticed that when using Stroop, sometime I do not understand what I should do. The color for example says "Black" and it's green, and the right choice is for example "Orange" and it's pink.

Can you reproduce?

**Comment by jaepo10** [comment]
I understand that the challenge is for your brain to be able to separate the visual stimulus from the concept and overcome that barrier. This contribution was made in English thanks to Google translate. My native language is Spanish.

**Comment by jaepo10** [comment]
By the way, I need to translate stroop into Spanish. I think my level of English is sufficient to make this contribution.

**Comment by fkropfhamer** [comment]
hey, you have to press the button with the name of the color of the given text. I will add explanations in upcoming versions. I think I will keep the app in english for now. But thank you for the offer.
